### ISSUE TITLE
Problems with testing FreeSurfer Installation

### ISSUE THREAD

**Issue by eternal7** [neurodebian/neurodebian#33]
I have followed the instructions from: http://nuclear-imaging.info/site_content/2016/09/12/installing-running-freesurfer-windows-10/
I have tested whether FreeSurfer worked properly from the site: https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall#TestyourFreeSurferInstallation
However, I've encountered problems at step 2. I think freesurfer did have been installed. But I have no way to see whether I can properly use it and track the results using freeview

eternal@DESKTOP-UNTM4IS:~$ recon-all -i sample-001.nii.gz -s bert -all
ERROR: You are trying to re-run an existing subject with (possibly)
 new input data (-i). If this is truly new input data, you should delete
 the subject folder and re-run, or specify a different subject name.
 If you are just continuing an analysis of an existing subject, then
 omit all -i flags.

Below are the 'bash' and lists of items for each directory.
 
eternal@DESKTOP-UNTM4IS:~$ bash
bash: /usr/local/freesurfer=/SetUpFreeSurfer.sh: no such file or directory
-------- freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /usr/local/freesurfer
FSFAST_HOME       /usr/local/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /usr/local/freesurfer/subjects
MNI_DIR           /usr/local/freesurfer/mni
FSL_DIR           /usr/share/fsl/5.0
-------- freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /usr/local/freesurfer
FSFAST_HOME       /usr/local/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /usr/local/freesurfer/subjects
MNI_DIR           /usr/local/freesurfer/mni
FSL_DIR           /usr/share/fsl/5.0
-------- freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /usr/local/freesurfer
FSFAST_HOME       /usr/local/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /usr/local/freesurfer/subjects
MNI_DIR           /usr/local/freesurfer/mni
FSL_DIR           /usr/share/fsl/5.0

eternal@DESKTOP-UNTM4IS:~$ ls
bashrc   freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz   matlab   sample-001.mgz   sample-001.nii.gz

eternal@DESKTOP-UNTM4IS:/usr/local/freesurfer$ ls
ASegStatsLUT.txt           NOTICE                     WMParcStatsLUT.txt   fsafd           sources.csh
AUTHORS                     README                     average                      fsfast          sources.sh
DefectLUT.txt                SegmentNoLUT.txt    bin                              lib               subjects
FreeSurferColorLUT.txt SetPuFreeSurfer.csh   build-stamp.txt          license.txt   tkmeditParcColorsCMA FreeSurferEnv.csh         SetUpFreeSurfer.sh    data                           matlab        tktools
FreeSurferEnv.sh          Simple_surface_labels2009.txt   diffusion     mni             trctrain
LICENSE                       VERSION                    docs                           sessions

eternal@DESKTOP-UNTM4IS:/usr/local/freesurfer/subjects$ ls
README    bert     cvs_avg35-inMNI152       fsaverage3   fsaverage5   fsaverage_sym   rh.EC_average   
sample-002.mgz   V1_average   cvs_avg35   fsaverage3   fsaverage4   fsaverage6        Ih.EC_average
sample-001.mgz

Thanks for reading!

**Comment by yarikoptic** [comment]
obviously something is funky/wrong in those lines you added to your .bashrc following the instructions you found online (step 9)
even more obvious -- it has nothing to do with NeuroDebian per se, thus closing.  Please seek support at the source of instructions of freesurfer forum
