### ISSUE TITLE
rclone version update ?

### ISSUE THREAD

**Issue by emdupre** [neurodebian/neurodebian#37]
I'm using rclone to set up a special (dropbox) remote for datalad, but if I use the [git-annex-remote-rclone  distributed with neurodebian](http://neuro.debian.net/pkgs/git-annex-remote-rclone.html), I'm unable to interface with the dropbox API, since neurodebian is pulling an older rclone (v1.36) than is currently supported.

I'm able to get around this by manually installing the latest rclone (v1.42) as detailed in the [git-annex special remotes instructions](https://git-annex.branchable.com/special_remotes/), but it would be great to have this right through neurodebian ! How could I go about updating the available version ?

Thank you, as always !

**Comment by yarikoptic** [comment]
Thank you for the report - we will look into YouTube the package, stay tuned ;-)

**Comment by yarikoptic** [comment]
btw, @emdupre - what is your base system (what release of debian/ubuntu?)

**Comment by emdupre** [comment]
Ubuntu 18.04, but tried on 16.04 as well !

**Comment by yarikoptic** [comment]
I've just uploaded 1.41 which we have in Debian to NeuroDebian -- would that be good enough or we do need 1.42 now (thought to be 'lazy' and just let Debian maintainer update it first)?

**Comment by emdupre** [comment]
v1.41 would be perfect :) It looks like the patch was pushed in v1.38.

Thanks again !!
