### ISSUE TITLE
nd_freeze: how well perl tolerates perl script being changed while running

### ISSUE THREAD

**Issue by yarikoptic** [neurodebian/neurodebian#42]
While chatting about nd_freeze, we came to realization that nd_freeze script might change while downgrading neurodebian-freeze package.  I know that bash does not really tolerate that.  Is perl ok with the script being changed while running.  E.g. add `sleep(10)` at the top, ~~remove~~ change the script, see if completes as expected

**Comment by yarikoptic** [comment]
attn @mjtravers (meanwhile adding you as a collaborator to this repo)

**Comment by mjtravers** [comment]
@yarikoptic A quick google search says perl loads the script file at the start so that changes to the script file in mid-run will not affect the run:

https://www.perlmonks.org/?node_id=979962
https://stackoverflow.com/questions/3618072/how-does-perl-interact-with-the-scripts-it-is-running

**Comment by yarikoptic** [comment]
Great! thank you!  then everything should cool even if there would be a downgrade of neurodebian-freeze during "roll back" step - it would freeze things properly without crashing ;-)
