### ISSUE TITLE
nd_freeze: security and updates aren't 

### ISSUE THREAD

**Issue by yarikoptic** [neurodebian/neurodebian#46]
Tried on this Singularity file:
```shell
$> cat Singularity.git-annex-dev
Bootstrap:docker
From:neurodebian:buster

%post
    echo "Configuring the environment"
    apt-get -y update

    echo "Freezing the environment"
    nd_freeze 2018/08/08

#    # setup the container sources themselves
#    apt-get -y install eatmydata vim less devscripts

%runscript
    #exec /bin/bash "$@"
    # Or let's just build the beast assuming we are in the directory with git-annex
    # sources
    make linuxstandalone

%environments
    unset PYTHONPATH
```
aforementioned `apt-get install` is commented out since it failed to install anything... so I was curious and thus built image without it to see:
```shell
$> cat /etc/apt/sources.list
# deb http://deb.debian.org/debian buster main
deb http://security.debian.org/debian-security buster/updates main
deb http://deb.debian.org/debian buster-updates main
```
so neither debian-security nor updates got their treatment to be replaced with entries from the Debian snapshots.

**Comment by mjtravers** [comment]
@yarikoptic I bet the regex that scans the sources.list is not picking up the lines to be commented out. I will look into this specific case. I imagine we might hit this type of problem a few more times as the script is released more and more into the wild.

**Comment by yarikoptic** [comment]
I thought that decisions on what snapshots to enable is done based on parsing output of `apt-cache policy` which is the only reliable way to identify origins etc.  It seems that here it is not just a matter or either they got commented out, but snapshots were not added at all
```shell
> grep '^d' -r /etc/apt/
/etc/apt/sources.list:deb http://security.debian.org/debian-security buster/updates main
/etc/apt/sources.list:deb http://deb.debian.org/debian buster-updates main
/etc/apt/sources.list.d/neurodebian.sources.list.orig.disabled:deb http://neuro.debian.net/debian buster main
/etc/apt/sources.list.d/neurodebian.sources.list.orig.disabled:deb http://neuro.debian.net/debian data main
/etc/apt/sources.list.d/snapshots.sources.list:deb http://snapshot.debian.org/archive/debian/20180808T024907Z/ buster main
/etc/apt/sources.list.d/snapshots.sources.list:deb http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z/ buster main
/etc/apt/sources.list.d/snapshots.sources.list:deb http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z/ data main
/etc/apt/sources.list.orig.disabled:deb http://deb.debian.org/debian buster main
/etc/apt/sources.list.orig.disabled:deb http://security.debian.org/debian-security buster/updates main
/etc/apt/sources.list.orig.disabled:deb http://deb.debian.org/debian buster-updates main
```

**Comment by yarikoptic** [comment]
ha - situation seems to be more tricky:
```shell
root@smaug:~# apt-get update
Hit:2 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z buster InRelease           
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [38.3 kB]                                       
Hit:3 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z data InRelease                                           
Get:4 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [47.6 kB]                                                          
Hit:5 http://snapshot.debian.org/archive/debian/20180808T024907Z buster InRelease    
Fetched 85.9 kB in 1s (64.6 kB/s)
Reading package lists... Done
root@smaug:~# apt-cache policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z data/main amd64 Packages
     release o=NeuroDebian,a=data,n=data,l=NeuroDebian,c=main,b=amd64
     origin snapshot-neuro.debian.net
 500 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z buster/main amd64 Packages
     release o=NeuroDebian,a=buster,n=buster,l=NeuroDebian,c=main,b=amd64
     origin snapshot-neuro.debian.net
 500 http://snapshot.debian.org/archive/debian/20180808T024907Z buster/main amd64 Packages
     release o=Debian,a=testing,n=buster,l=Debian,c=main,b=amd64
     origin snapshot.debian.org
Pinned packages:
```
so why security isn't listed?  http://security-cdn.debian.org/debian-security/dists/buster/updates/Release seems to  have a dedicated label.

As for my problem with installing -- seems to boil down to really needing to roll back those versions of the core packages to the state of buster at that point.  So I will eagerly waiting for https://github.com/neurodebian/neurodebian/pull/45 to do it in one line to give it a shot.  This specific usecase -- buster (which is current testing) downgrade to e.g. this august -- could be a good test case

**Comment by yarikoptic** [comment]
the reason seems to be - APT sources currently without packages are not listed :-(  original report and self-reply is at http://bugs.debian.org/913913

I wonder if instead of using `apt-cache policy` we should go through `/var/lib/apt/lists/*Release` files -- all information we need, but the url which is "encoded" in the filename, is in their header....  what do you think @mjtravers ?

This situation though is most likely relevant only for Debian testing, where those apt repositories are typically empty and otherwise wouldn't likely to happen.

**Comment by mjtravers** [comment]
@yarikoptic 
So, if I am following all this correctly, the is the idea here to pull the Release files based on the date submitted from the user and then piece together the snapshots.sources.list lines needed based on the architecture and distribution the user is currently using?

For example: A neurodebian wheezy system whose user wanted to freeze back to 10/14/2015 would get the NeuroDebian Release file from here:

http://snapshot-neuro.debian.net:5002/archive/neurodebian/20151014T050502Z/dists/wheezy/Release

And then pull, say, the binary amd64 (if that's what they are on) lines (from the MD5Sum section in the Release file):

 b009fe92f00f4e9e315c4dedfaa9cf40 211 main/binary-amd64/Release
 efff10e784ca092e4b682b9be1c72664 215 non-free/binary-amd64/Release
 10eb51a43014f26adcdcbf04aea7ed49 214 contrib/binary-amd64/Release

And then from there, create a snapshots.sources.list entry such as:

deb http://snapshot-neuro.debian.net:5002/archive/neurodebian/20151014T050502Z/ wheezy main non-free contrib

Whereas the same exercise using our current "apt-cache policy strategy" acquires the lines:

deb http://snapshot-neuro.debian.net:5002/archive/neurodebian/20151014T050502Z/ data main
deb http://snapshot-neuro.debian.net:5002/archive/neurodebian/20151014T050502Z/ wheezy main

Yes? Maybe do the "apt-cache policy strategy" and then augment the results by scanning the snapshot Release files?

**Comment by yarikoptic** [comment]
No, it is simply to go though `/var/lib/apt/lists/*Release` files instead of apt cache policy output

**Comment by mjtravers** [comment]
Ah, so I was close yet so far far away.

And I see that I can just pull the information needed to create the snapshots.sources.list entries from the header of the *Release files:

root@650f1635f9b4:/var/lib/apt/lists# head -10 *Release
==> deb.debian.org_debian_dists_wheezy-updates_Release <==
Origin: Debian
Label: Debian
Suite: oldoldstable-updates
Codename: wheezy-updates
Date: Wed, 24 Jan 2018 08:51:34 UTC
Architectures: amd64 armel armhf i386 ia64 kfreebsd-amd64 kfreebsd-i386 mips mipsel powerpc s390 s390x sparc
Components: main contrib non-free
Description: Updated packages for Debian 7.0
MD5Sum:
 d41d8cd98f00b204e9800998ecf8427e        0 contrib/Contents-amd64

==> deb.debian.org_debian_dists_wheezy_Release <==
Origin: Debian
Label: Debian
Suite: oldoldstable
Version: 7.11
Codename: wheezy
Date: Sat, 17 Jun 2017 08:55:32 UTC
Architectures: amd64 armel armhf i386 ia64 kfreebsd-amd64 kfreebsd-i386 mips mipsel powerpc s390 s390x sparc
Components: main contrib non-free
Description: Debian 7.11 Released 04 June 2016
MD5Sum:

==> neuro.debian.net_debian_dists_data_Release <==
Origin: NeuroDebian
Label: NeuroDebian
Suite: data
Codename: data
Date: Wed, 24 Jan 2018 15:26:17 UTC
Architectures: i386 amd64 sparc armel mipsel
Components: main non-free contrib
Description: NeuroDebian datasets repository
MD5Sum:
 e3ae57bce6be35726facb946d584e982 24465 main/binary-i386/Packages

==> neuro.debian.net_debian_dists_wheezy_Release <==
Origin: NeuroDebian
Label: NeuroDebian
Suite: wheezy
Codename: wheezy
Date: Wed, 21 Nov 2018 20:32:41 UTC
Architectures: i386 amd64 sparc armel
Components: main non-free contrib
Description: NeuroDebian repository with perspective, inofficial and backported packages -- mostly neuroscience-related
MD5Sum:
 7a6077bbf4c2aae316b2722cee197afe 547335 main/binary-i386/Packages

==> security.debian.org_debian-security_dists_wheezy_updates_Release <==
Origin: Debian
Label: Debian-Security
Suite: oldoldstable
Version: 7.0
Codename: wheezy
Date: Wed, 28 Nov 2018 22:01:32 UTC
Valid-Until: Sat, 08 Dec 2018 22:01:32 UTC
Architectures: amd64 armel armhf i386
Components: updates/main updates/contrib updates/non-free
Description: Long Term Support for Debian 7
