### ISSUE TITLE
nd_freeze: Reduce verbosity on downgrades

### ISSUE THREAD

**Issue by yarikoptic** [neurodebian/neurodebian#48]
Trying to freeze buster back to 2018/05/18 -- keeps flooding the screen with all the announcements of analysis and what it would downgrade, e.g.
```
...
INFO: Will DOWNGRADE 'gcc-8-base:amd64=8.2.0-9' to version '8.1.0-3'
INFO: Checking package 'gnupg' for an older snapshot version
...
```
Probably shift this to "debug" ("--debug" or "-d" switch) level and otherwise just announce total # of packages to be downgraded.
Unless in --debug mode, `apt-get install` for those should also get `-q` option added to not flood the screen with all the reports on getting older versions.

**Comment by mjtravers** [comment]
Issue resolved in PR #49
