### ISSUE TITLE
Can someone help me how can i download .iso file which contains preinstalled GENESIS,XPAUT,NEURON,PYTHON..

### ISSUE THREAD

**Issue by INNFINITEMINDS** [neurodebian/neurodebian#52]
Help required I want to download an iso file that contain preinstalled tools..
Looking forward for your response
.

Thanks in advance..

**Comment by yarikoptic** [comment]
There used to be some live images floating around, which we listed at http://neuro.debian.net/derivatives.html but not sure which are still alive and which new ones are out there targeting neuro modeling. When you discover new ones, please send a or updating that page or just let us know
