### ISSUE TITLE
fsl-complete not found

### ISSUE THREAD

**Issue by ch-n** [neurodebian/neurodebian#72]
Hi, 
I'm using the latest version of neurodebian to create a singularity image, but I'm unabble to install fsl by sudo apt-get install fsl-complete. The error code is the following:

sudo apt-get update
sudo apt-get install fsl-complete

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fsl-complete

I would highly appreciate your help,
Chris

**Comment by yarikoptic** [comment]
Probably you would want a more recent fsl anyways, so may be try https://github.com/ReproNim/neurodocker . Although it might need some work too https://github.com/ReproNim/neurodocker/pull/312
